### ISSUE TITLE
Possible unnecessary dependencies for mac.

### ISSUE THREAD

**Issue by crluna** [sebjameswml/brahms#9]
When trying to build it for max os I get a dependency error, the relevant part of the error says:

Found X11: /usr/X11R6/lib/libX11.dylib
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.28")
-- checking for module 'xaw7'
-- package 'xaw7' not found
CMake Error at /usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/FindPkgConfig.cmake:341 (message):
A required package was not found
Call Stack (most recent call first):
/usr/local/Cellar/cmake/3.0.2/share/cmake/Modules/FindPkgConfig.cmake:395 (_pkg_check_modules_internal)
BrahmsLibFind.cmake:121 (pkg_check_modules)
CMakeLists.txt:140 (include)

CMake Error at BrahmsLibFind.cmake:127 (message):
You need libXaw7. On Debian/Ubuntu try sudo apt-get install libxaw7-dev
Call Stack (most recent call first):
CMakeLists.txt:140 (include)

I was told perhaps this is an unnecessary dependency.

**Comment by ajc158** [comment]
IIRC BRAHMS' old makefiles had an option for compiling without X11, which I think contributes to creating the problem here as we don't need X11 support for SML_2_BRAHMS - I guess the hooks should still be there @sebjameswml ?

**Comment by ajc158** [comment]
Ok, I have hacked a version at https://github.com/ajc158/BRAHMSnoX11Hack which has no X11 dep and seems to compile and run ok on my Mac (not extensively tested tho!). We'll need to work out how to add these changes into the main repo in a more elegant way!

**Comment by sebjameswml** [comment]
Hi Alex, when you're happy with the changes, you could issue a pull request.

**Comment by sebjameswml** [comment]
I've merged the pull request - see commit 1aaad3b
